import {
  collection,
  doc,
  addDoc,
  getDoc,
  getDocs,
  setDoc,
  updateDoc,
  serverTimestamp,
  query,
} from "firebase/firestore";
import { db, auth } from "../config";
import { InputState } from "@/app/lib/typesAndInterfaces";

export async function getUserSnapshot() {
  // only need to retrieve displayName when fetching data
  const currentUser = auth.currentUser?.displayName;
  try {
    if (!currentUser) {
      throw new Error("No current user found.");
    }
    const q = query(collection(db, currentUser));
    const querySnapshot = await getDocs(q);
    console.log("querySnapshot in getUserSnapshot:", querySnapshot);

    const res = querySnapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    }));
    return {
      success: true,
      message: `Successfully fetched ${currentUser} data`,
      error: null,
      res,
    };
  } catch (err) {
    return {
      success: false,
      message: `Error fetching ${currentUser || "unknown user"} data: ${err}`,
      error: err,
    };
  }
}

async function setStudentData(formInput: InputState, currentUser: string) {
  try {
    await setDoc(doc(db, `${currentUser}`, "formInput"), {
      ...formInput,
      createdAt: serverTimestamp(),
    });
    return true;
  } catch (e) {
    console.error("setStudentData error: ", e);
    return false;
  }
}

async function updateStudentData(formInput: InputState, currentUser: string) {
  try {
    const docRef = doc(db, `${currentUser}`, "formInput");
    await updateDoc(docRef, {
      ...formInput,
      updatedAt: serverTimestamp(),
    });
    return true;
  } catch (e) {
    console.error("updateStudentData error: ", e);
    return false;
  }
}

export async function setOrUpdateStudentData(
  formInput: InputState,
  currentUser: string
) {
  try {
    const docRef = doc(db, `${currentUser}`, "formInput");
    const docSnap = await getDoc(docRef);
    console.log("docSnap.exists(): ", docSnap.exists());

    if (docSnap.exists()) {
      await updateStudentData(formInput, currentUser);
    } else {
      await setStudentData(formInput, currentUser);
    }
    return true;
  } catch (e) {
    console.error("setOrUpdateStudentData error: ", e);
    return false;
  }
}

// export async function getDataFromUser(currentUser) {
//   try {
//     const docRef = doc(db, `${currentUser}`, "formInput");
//     const docSnap = await getDoc(docRef);

//     if (docSnap.exists()) {
//       console.log("Document data:", docSnap.data());
//     } else {
//       console.log("No such document! docSnap.data() is undefined.");
//     }
//   } catch (err) {
//     console.error("getDataFromUser error:", err);
//   }
// }

// export async function addKeySigData(first, second, third, fourth, currentUser) {
//   try {
//     const docRef = await addDoc(collection(db, `${currentUser}`), {
//       first: first,
//       second: second,
//       third: third,
//       fourth: fourth,
//       createdAt: serverTimestamp(),
//       updatedAt: serverTimestamp(),
//     });
//     // The addDoc creates a new document with a unique ID, and then adds the data to that document. The document ID is automatically generated by Firestore.
//     console.log("Document written with ID: ", docRef.id);
//     return true;
//   } catch (e) {
//     console.error("addKeySigData error: ", e);
//     return false;
//   }
// }

// export async function setKeySigData(collection, id, data) {
//   try {
//     // this doc creates the reference to the document - i.e. where is it?
//     // collection could be "lr" or "messages" in this example, or it could be a path to a subcollection, like "lr/album1"
//     const docRef = doc(db, collection, id);
//     // setDoc is the mutation function that actually adds the data to the database - let me update the server
//     // on the Frontend masters video, he says await is not needed here and it could be actually worse to use it. The purpose of await is to wait for the response from the server, but if you don't need the response, then you don't need await. Firestore autmatically handles the response from the server, so you don't need to wait for it.
//     // also note that setDoc adds data destructively - i.e. it will overwrite any existing data at that location
//     const result = await setDoc(docRef, data, {
//       merge: true,
//     });
//     return { result, error: null };
//   } catch (error) {
//     console.error("addData error:", error);
//     return { result: null, error: error.message };
//   }
// }
